[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "10.15.3"

[dev]
  command = "npm run start"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
package = "netlify-deployment-hours-plugin"

  [plugins.inputs]
  # A cron-like expression that expresses when a deployment can occur
  expression = "* * * * *"
  # tz database value that expresses the timezone of the expression
  timezone = "America/Chicago"